- hosts: local
  gather_facts: False
  vars:
    dict: 
      { 
      pedro: '/home/user1', 
      joao: '/home/user1',
      daniel: '/home/gerente1',
      luiz: '/home/diretor1'
      }
  tasks:
  - name: Exibindo variaveis
    debug: 
      msg: "Chave é {{ item.key}} e o valor {{item.value}}"
    with_dict: "{{ dict }}"
