- hosts: local
  gather_facts: False
  vars:
    pacotes:
      - sysstat
      - docker
      - nginx

  
  tasks:
  - name: Exibindo variaveis
    debug: 
      msg: "{{ item.name }} - {{ item.user }} {{ item.group }} {{ item.chmod }} "
    loop:
      - name: Dockerfile
        user: root
        group: root
        chmod: 755
      - name: docker-compose.yml
        user: vagrant
        group: vagrant
        chmod: 644
